name       : haskell-infer-license
version    : 0.2.0
release    : 1
source     :
    - https://hackage.haskell.org/package/infer-license-0.2.0/infer-license-0.2.0.tar.gz : 12e6fe616575159c03cf6fd4a4f30021ecf264a529ab4e4edd6e96e296a98e72
license    : MIT
component  : programming.haskell
summary    : Infer software license from a given license file
description: |
    Infer software license from a given license file
builddeps  :
    - haskell-cabal-install
    - haskell-text-metrics-devel
rundeps    :
    - devel:
        - haskell-text-metrics-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
